<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Libro;

class LibroSeeder extends Seeder
{
    public function run(): void
    {
        Libro::insert([
            [
                'titulo' => 'Orgullo y Prejuicio',
                'autor' => 'Jane Austen',
                'isbn' => '978000000001',
                'descripcion' => 'Clásico de romance.',
                'genero' => 'Romance',
                'idioma' => 'Español',
                'anio_publicacion' => 1813,
                'portada' => 'orgullo-prejuicio.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La Abeja Maya',
                'autor' => 'Waldemar Bonsels',
                'isbn' => '978000000002',
                'descripcion' => 'Libro infantil clásico.',
                'genero' => 'Infantil',
                'idioma' => 'Español',
                'anio_publicacion' => 1912,
                'portada' => 'la-abeja-maya.jpg',
                'clasificacion_edad' => 'infantil',
                'max_prestamos' => 3,
                'categoria_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'El Niño con el Pijama de Rayas',
                'autor' => 'John Boyne',
                'isbn' => '978000000003',
                'descripcion' => 'Historia ambientada en la guerra.',
                'genero' => 'Drama',
                'idioma' => 'Español',
                'anio_publicacion' => 2006,
                'portada' => 'el-nino-pijama-rayas.jpg',
                'clasificacion_edad' => 'juvenil',
                'max_prestamos' => 3,
                'categoria_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Cumbres Borrascosas',
                'autor' => 'Emily Brontë',
                'isbn' => '978000000004',
                'descripcion' => 'Drama romántico clásico.',
                'genero' => 'Romance',
                'idioma' => 'Español',
                'anio_publicacion' => 1847,
                'portada' => 'cumbres-borrascosas.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Dune',
                'autor' => 'Frank Herbert',
                'isbn' => '978000000005',
                'descripcion' => 'Ciencia ficción épica.',
                'genero' => 'Ciencia ficción',
                'idioma' => 'Español',
                'anio_publicacion' => 1965,
                'portada' => 'dune.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'The Sandman',
                'autor' => 'Neil Gaiman',
                'isbn' => '978000000006',
                'descripcion' => 'Cómic oscuro de fantasía.',
                'genero' => 'Fantasía',
                'idioma' => 'Español',
                'anio_publicacion' => 1989,
                'portada' => 'the-sandman.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Fahrenheit 451',
                'autor' => 'Ray Bradbury',
                'isbn' => '978000000007',
                'descripcion' => 'Distopía clásica.',
                'genero' => 'Ciencia ficción',
                'idioma' => 'Español',
                'anio_publicacion' => 1953,
                'portada' => 'f-451.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'La chica mecánica',
                'autor' => 'Paolo Bacigalupi',
                'isbn' => '978000000008',
                'descripcion' => 'Futurista y distópico.',
                'genero' => 'Ciencia ficción',
                'idioma' => 'Español',
                'anio_publicacion' => 2009,
                'portada' => 'la-chica-mecanica.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'El Marciano',
                'autor' => 'Andy Weir',
                'isbn' => '978000000009',
                'descripcion' => 'Supervivencia en Marte.',
                'genero' => 'Ciencia ficción',
                'idioma' => 'Español',
                'anio_publicacion' => 2011,
                'portada' => 'el-marciano.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'De sangre y ceniza',
                'autor' => 'Jennifer L. Armentrout',
                'isbn' => '978000000010',
                'descripcion' => 'Romance fantástico.',
                'genero' => 'Fantasía',
                'idioma' => 'Español',
                'anio_publicacion' => 2020,
                'portada' => 'de-sangre-y-ceniza.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Ofrendas de verano',
                'autor' => 'J. L. López',
                'isbn' => '978000000011',
                'descripcion' => 'Novela contemporánea.',
                'genero' => 'Drama',
                'idioma' => 'Español',
                'anio_publicacion' => 2018,
                'portada' => 'ofrendas-de-verano.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Una corte de niebla y furia',
                'autor' => 'Sarah J. Maas',
                'isbn' => '978000000012',
                'descripcion' => 'Fantasía romántica.',
                'genero' => 'Fantasía',
                'idioma' => 'Español',
                'anio_publicacion' => 2016,
                'portada' => 'corte-niebla-furia.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Ciudad de Hueso',
                'autor' => 'Cassandra Clare',
                'isbn' => '978000000013',
                'descripcion' => 'Cazadores de sombras.',
                'genero' => 'Fantasía',
                'idioma' => 'Español',
                'anio_publicacion' => 2007,
                'portada' => 'cazadores-sombras-ciudad-hueso.jpg',
                'clasificacion_edad' => 'juvenil',
                'max_prestamos' => 3,
                'categoria_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Entrevista con el vampiro',
                'autor' => 'Anne Rice',
                'isbn' => '9780000000017',
                'descripcion' => 'Vampiros.',
                'genero' => 'Terror',
                'idioma' => 'Español',
                'anio_publicacion' => 1976,
                'portada' => 'entrevista-vampiro.jpg',
                'clasificacion_edad' => 'adulto',
                'max_prestamos' => 3,
                'categoria_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'El Principito',
                'autor' => 'Antoine de Saint-Exupéry',
                'isbn' => '978000000014',
                'descripcion' => 'Obra filosófica.',
                'genero' => 'Fábula',
                'idioma' => 'Español',
                'anio_publicacion' => 1943,
                'portada' => 'el-principito.jpg',
                'clasificacion_edad' => 'infantil',
                'max_prestamos' => 3,
                'categoria_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Resuelve el misterio',
                'autor' => 'Lauren Farnsworth',
                'isbn' => '978000000015',
                'descripcion' => 'Novela de misterio.',
                'genero' => 'Misterio',
                'idioma' => 'Español',
                'anio_publicacion' => 2019,
                'portada' => 'resuleve-el-misterio.jpeg',
                'clasificacion_edad' => 'juvenil',
                'max_prestamos' => 3,
                'categoria_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Harry Potter y la piedra filosofal',
                'autor' => 'J.K. Rowling',
                'isbn' => '978000000016',
                'descripcion' => 'Inicio de la saga.',
                'genero' => 'Fantasía',
                'idioma' => 'Español',
                'anio_publicacion' => 1997,
                'portada' => 'harry-potter1.jpg',
                'clasificacion_edad' => 'juvenil',
                'max_prestamos' => 3,
                'categoria_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
